apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-exporter
  namespace: homelab
spec:
  interval: 10m
  chart:
    spec:
      chart: prometheus-node-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: homelab
      interval: 10m
  values:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi
    tolerations:
      - effect: NoSchedule
        operator: Exists
    hostNetwork: true
    hostPID: true
