# .yamllint
extends: default

rules:
  document-start: disable      # Flux & Helm templates often omit ---
  truthy:
    allowed-values: ['true', 'false', 'on']
  line-length:
    max: 120                   # Helm values can get long
    level: warning
  indentation:
    spaces: 2
    indent-sequences: consistent
  comments:
    min-spaces-from-content: 1
