# .yamllint
extends: default

ignore: |
  **/charts/**/templates/**
  **/*.tpl
  **/flux-system/gotk-components.yaml
  **/flux-system/gotk-sync.yaml

rules:
  empty-lines:
    max: 2
    max-start: 1
    max-end: 1
    level: warning

  new-line-at-end-of-file: disable
  document-start: disable

  trailing-spaces: disable

  line-length:
    max: 120
    level: warning

  comments:
    level: warning

  indentation:
    spaces: 2
    indent-sequences: consistent

  key-duplicates: enable
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
