apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: homelab
spec:
  interval: 10m
  chart:
    spec:
      chart: grafana
      version: "8.5.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: homelab
  values:
    grafana:
      sidecar:
        dashboards:
          enabled: true
        datasources:
          enabled: true
    persistence:
      enabled: true
      size: 5Gi
    adminUser: admin
    adminPassword: testpassword  # replace with sealed secret
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi
    service:
      type: ClusterIP