apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: homelab
spec:
  url: https://prometheus-community.github.io/helm-charts
  interval: 24h
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana
  namespace: homelab
spec:
  url: https://grafana.github.io/helm-charts
  interval: 24h
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: homelab
spec:
  url: https://charts.bitnami.com/bitnami
  interval: 24h
---
# grafana and loki charts are under the same grafana repo
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana-loki
  namespace: homelab
spec:
  url: https://grafana.github.io/helm-charts
  interval: 24h