apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prom-stack
  namespace: homelab
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "45.6.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: homelab
  values:
    prometheus:
      prometheusSpec:
        resources:
          requests:
            cpu: 300m
            memory: 512Mi
          limits:
            cpu: 700m
            memory: 1Gi
        retention: 24h
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 5Gi
    alertmanager:
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 200m
          memory: 512Mi
    grafana:
      enabled: true
      sidecar:
        dashboards:
          enabled: true
    kubeStateMetrics:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    nodeExporter:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi