apiVersion: v1
kind: Service
metadata:
  name: postgres-lb
  namespace: databases
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.244
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgres
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
