apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: homelab
spec:
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
      interval: 1h
  releaseName: metallb
  interval: 10m
  values:
    controller:
      resources:
        requests:
          cpu: 200m
          memory: 125Mi
        limits:
          cpu: 500m
          memory: 512Mi