apiVersion: apps/v1
kind: Deployment
metadata:
  name: glance
  namespace: homelab
  labels:
    app: glance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glance
  template:
    metadata:
      labels:
        app: glance
    spec:
      containers:
        - name: glance
          image: glanceapp/glance:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "50m"
              memory: "1Gi"
            limits:
              cpu: "100m"
              memory: "256Mi"
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: TZ
              value: "Asia/Kolkata"
            - name: MY_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: glance-secret
                  key: MY_SECRET_TOKEN
          # mount the config file from the ConfigMap as /app/config/glance.yml
          volumeMounts:
            - name: glance-config
              mountPath: /app/config/glance.yml
              subPath: glance.yml
      volumes:
        - name: glance-config
          configMap:
            name: glance-config
            items:
              - key: glance.yml
                path: glance.yml