apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glance-ingress
  namespace: homelab
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "ca-issuer"
spec:
  tls:
    - hosts:
        - glance.home.lab
      secretName: glance-tls
  rules:
    - host: glance.home.lab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: glance
                port:
                  number: 8080