
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  dependOn:
    - name: metallb-config
  interval: 10m0s
  path: ./infrastructure/olympus
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
