apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: homelab
spec:
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
      #version: "6.4.x"
      interval: 24h
  releaseName: metrallb
  interval: 24h
  values:
    controller:
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: 150m
          memory: 512Mi