apiVersion: v1
kind: Namespace
metadata:
  name: metallb-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: metallb-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: containous/whoami:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-lb
  namespace: metallb-test
spec:
  type: LoadBalancer
  selector:
    app: whoami
  ports:
  - port: 80
    targetPort: 80