apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: containous/whoami:latest
        ports:
        - containerPort: 81
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-lb
  namespace: homelab
spec:
  type: LoadBalancer
  selector:
    app: whoami
  ports:
  - port: 81
    targetPort: 81