apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: homelab
spec:
  chart:
    spec:
      chart: nginx-ingress
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      version: "2.3.x"
      interval: 1h
  releaseName: nginx-ingress
  interval: 10m
  values:
    controller:
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 200m
          memory: 512Mi
      service:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.243 # optional: reserve a fixed IP from your pool
        externalTrafficPolicy: Cluster
