apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: homelab-ip-pool
  namespace: homelab
spec:
  addresses:
    - 192.168.1.240-192.168.1.245
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: homelab-l2
  namespace: homelab
spec:
  ipAddressPools:
    - homelab-ip-pool
